using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Infrastructure.Data;
using Core.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Sqlite;
using Microsoft.EntityFrameworkCore;

/*ControllerBaseden miras ver 
using Microsoft.AspNetCore.Mvc ; usingini ekle 
[ApiController]
[Route("api/[controller]")]
attribute lerini tanımla 
 yukarıdaki 4 kutuphane zaten autogenerated kısmından üretildiği için silebilirsin gerek yok
*/
namespace API.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ProductsController : ControllerBase
    {
        private readonly StoreContext _context;
       public ProductsController(StoreContext context)
       {
            _context = context;
        
       }

        [HttpGet]
        public async  Task<ActionResult<List<Product>>> GetProducts()
        {
            return await _context.Products.ToListAsync();
            
        }
        [HttpGet("{id}")]
        public async Task<ActionResult<Product>> GetProducts(int id)
        {
            return await _context.Products.FindAsync(id);
        }
    }
}